@Api_HostAddress = http://localhost:5058
###
// ROL
// Ver todos los roles
GET {{Api_HostAddress}}/api/roles/
Accept: application/json
###
// Obtener rol especifico
GET {{Api_HostAddress}}/api/rol?idRol=a1d3a394-1bbf-4d98-8c46-c52c6c14a992
Accept: application/json
###
// Crear rol
POST {{Api_HostAddress}}/api/rol/
Content-Type: application/json
{
    "Nombre": "delegado",
    "Habilitado": true
}
###
// Actualizar rol
PUT {{Api_HostAddress}}/api/rol?idRol=ca98c96f-73a3-4ec3-8491-aeccb449ef10
Content-Type: application/json
{
    "Nombre": "rector",
    "Habilitado": false
}
###
// Eliminar rol
DELETE {{Api_HostAddress}}/api/rol?idrol=43771f2c-3b97-4478-9544-b2c966eabe13
Accept: application/json
### 

// USUARIO
// Ver todos los usuarios
GET {{Api_HostAddress}}/api/usuarios/
Accept: application/json
###
// Obtener usuario especifico
GET {{Api_HostAddress}}/api/usuario?idUsuario=1
Accept: application/json
###
// Crear usuario
POST {{Api_HostAddress}}/api/usuario/
Content-Type: application/json
{
    "Nombre": "Juan",
    "Email":"juanet12d1@gmail.com",
    "NombreUsuario":"juan-15kh",
    "Contrasena":"hola1234", 
    "Habilitado": true
}
###
// Actualizar usuario
PUT {{Api_HostAddress}}/api/usuario?idUsuario=3
Content-Type: application/json
{
    "Nombre":"priscila",
    "Email":"priscilaet12d1@gmail.com",
    "NombreUsuario":"pri.indumentaria.h@gmail.com",
    "Contrasena":"caperucita"
}
###
// Eliminar usuario
DELETE {{Api_HostAddress}}/api/usuario?idUsuario=3
Accept: application/json
###

// Relacion usuario y rol
// rol a usuario
POST {{Api_HostAddress}}/api/rol/ca98c96f-73a3-4ec3-8491-aeccb449ef10/usuario/2
Content-Type: application/json
###
DELETE {{Api_HostAddress}}/api/rol/ca98c96f-73a3-4ec3-8491-aeccb449ef10/usuario/2
Content-Type: application/json
###
// usuario a rol
POST {{Api_HostAddress}}/api/usuario/3/rol/43771f2c-3b97-4478-9544-b2c966eabe13
Content-Type: application/json
###
DELETE {{Api_HostAddress}}/api/usuario/3/rol/43771f2c-3b97-4478-9544-b2c966eabe13
Content-Type: application/json
###