@Api_HostAddress = http://localhost:5058
###
// ROL
// Ver todos los roles
GET {{Api_HostAddress}}/api/roles/
Accept: application/json
###
// Obtener rol especifico
GET {{Api_HostAddress}}/api/rol?idRol=ca98c96f-73a3-4ec3-8491-aeccb449ef10
Accept: application/json
###
// Crear rol
POST {{Api_HostAddress}}/api/rol/
Content-Type: application/json
{
    "Nombre": "Delegado",
    "Habilitado": true
}
###
// Actualizar rol
PUT {{Api_HostAddress}}/api/rol?idRol=6fbc67c7-9ed0-495c-b4d4-8b0446194eed
Content-Type: application/json
{
    "Nombre": "estudiante",
    "Habilitado": false
}
###
// Eliminar rol
DELETE {{Api_HostAddress}}/api/rol?idrol=ca98c96f-73a3-4ec3-8491-aeccb449ef10
Accept: application/json
### 

// USUARIO
// Ver todos los usuarios
GET {{Api_HostAddress}}/api/usuarios/
Accept: application/json
###
// Obtener usuario especifico
GET {{Api_HostAddress}}/api/usuario?idUsuario=1
Accept: application/json
###
// Crear usuario
POST {{Api_HostAddress}}/api/usuario/
Content-Type: application/json
{
    "Nombre": "fdṕasdkpśfksdñlf{}",
    "Email":"iliana.duarte@gmail.com",
    "NombreUsuario":"iliduarte",
    "Contrasena":"floresAmarillas"
}
###
// Actualizar usuario
PUT {{Api_HostAddress}}/usuario?idUsuario=2
Content-Type: application/json
{
    "Nombre":"Priscila",
    "Email":"priet12@gmail.com",
    "NombreUsuario":"pri.indumentaria@gmail.com",
    "Contraseña":"michis"
}
###
// Eliminar usuario
DELETE {{Api_HostAddress}}/usuario?idUsuario=3
Accept: application/json
###

// Relacion usuario y rol
// rol a usuario
POST {{Api_HostAddress}}/rol/3/usuario/1
Content-Type: application/json
###
DELETE {{Api_HostAddress}}/rol/3/usuario/1
Content-Type: application/json
###
// usuario a rol
POST {{Api_HostAddress}}/usuario/1/rol/2
Content-Type: application/json
###
DELETE {{Api_HostAddress}}/usuario/1/rol/2
Content-Type: application/json
###